<?php
namespace Fecdas\PartesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

# sudo -u www-data php app/console doctrine:generate:entities FecdasPartesBundle:EntityUserLog

/**
 * @ORM\Entity
 * @ORM\Table(name="m_userslog")
 * 
 * @author alex
 *
 */
class EntityUserLog {
	
	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;
	
	/**
	 * @ORM\Column(type="string", length=50)
	 * @ORM\ManyToOne(targetEntity="EntityUser")
	 * @ORM\JoinColumn(name="user", referencedColumnName="user")
	 */
	protected $user;	// Mail del club

	/**
	 * @ORM\Column(type="string", length=20)
	 */
	protected $accio;

	/**
	 * @ORM\Column(type="datetime")
	 */
	protected $timestamp;
	
	/**
	 * @ORM\Column(type="string", length=20, nullable=true)
	 */
	protected $remoteaddr;
	
	/**
	 * @ORM\Column(type="string", length=100, nullable=true)
	 */
	protected $useragent;

	/**
	 * @ORM\Column(type="string", length=100, nullable=true)
	 */
	protected $extrainfo;

	public function __construct($user, $accio, $remoteaddr = null, $useragent = null, $extrainfo = null) {
		
		$this->user = $user;
		$this->accio = $accio;
		$this->timestamp = new \DateTime('now');
		$this->remoteaddr = $remoteaddr;
		$this->useragent = $useragent;
		$this->extrainfo = $extrainfo;
	}
	
	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}
	
	// Set Id not autogenerated
	/**
	 * Set id
	 *
	 * @param integer $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}
	
    /**
     * Set user
     *
     * @param string $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * Get user
     *
     * @return string 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set accio
     *
     * @param string $accio
     */
    public function setAccio($accio)
    {
        $this->accio = $accio;
    }

    /**
     * Get accio
     *
     * @return string 
     */
    public function getAccio()
    {
        return $this->accio;
    }

    /**
     * Set datetime
     *
     * @param datetime $timestamp
     */
    public function setTimestamp($timestamp)
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Get timestamp
     *
     * @return datetime 
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Set remoteaddr
     *
     * @param string $remoteaddr
     */
    public function setRemoteaddr($remoteaddr)
    {
        $this->remoteaddr = $remoteaddr;
    }

    /**
     * Get remoteaddr
     *
     * @return string 
     */
    public function getRemoteaddr()
    {
        return $this->remoteaddr;
    }

    /**
     * Set useragent
     *
     * @param string $useragent
     */
    public function setUseragent($useragent)
    {
        $this->useragent = $useragent;
    }

    /**
     * Get useragent
     *
     * @return string 
     */
    public function getUseragent()
    {
        return $this->useragent;
    }

    /**
     * Set extrainfo
     *
     * @param string $extrainfo
     */
    public function setExtrainfo($extrainfo)
    {
        $this->extrainfo = $extrainfo;
    }

    /**
     * Get extrainfo
     *
     * @return string 
     */
    public function getExtrainfo()
    {
        return $this->extrainfo;
    }
}