#FecdasPartesBundle_homepage:
#    pattern:  /fecdas/{name}
#    defaults: { _controller: FecdasPartesBundle:Default:index }

FecdasPartesBundle_homepage:
    pattern:  /
    defaults: { _controller: "FecdasPartesBundle:Page:index" }
    requirements:
        _scheme:  http
        _method:  GET
        
FecdasPartesBundle_contact:
    pattern:  /contact
    defaults: { _controller: "FecdasPartesBundle:Page:contact" }
    requirements:
        _scheme:  http
        _method:  GET|POST

FecdasPartesBundle_login:
    pattern:  /login
    defaults: { _controller: "FecdasPartesBundle:Security:login" }
    requirements:
        _scheme:  https
        _method:  GET|POST

FecdasPartesBundle_pwdrecovery:
    pattern:  /pwdrecovery
    defaults: { _controller: "FecdasPartesBundle:Security:pwdrecovery" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_user:
    pattern:  /user
    defaults: { _controller: "FecdasPartesBundle:Security:user" }
    requirements:
        _method:  GET|POST


FecdasPartesBundle_logout:
    pattern:  /logout
    defaults: { _controller: "FecdasPartesBundle:Security:logout" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_club:
    pattern:  /club
    defaults: { _controller: "FecdasPartesBundle:Security:club" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_usuariclub:
    pattern:  /usuariclub
    defaults: { _controller: "FecdasPartesBundle:Security:usuariclub" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_changerole:
    pattern:  /changerole
    defaults: { _controller: "FecdasPartesBundle:Admin:changerole" }
    requirements:
        _method:  GET

FecdasPartesBundle_recents:
    pattern:  /recents
    defaults: { _controller: "FecdasPartesBundle:Admin:recents" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_clubs:
    pattern:  /clubs
    defaults: { _controller: "FecdasPartesBundle:Admin:clubs" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_canviestatclub:
    pattern:  /canviestatclub
    defaults: { _controller: "FecdasPartesBundle:Admin:canviestatclub" }
    requirements:
        _method:  GET

FecdasPartesBundle_confirmapagament:
    pattern:  /confirmapagament
    defaults: { _controller: "FecdasPartesBundle:Admin:confirmapagament" }
    requirements:
        _method:  GET

FecdasPartesBundle_sincroaccess:
    pattern:  /sincroaccess
    defaults: { _controller: "FecdasPartesBundle:Admin:sincroaccess" }
    requirements:
        _method:  GET

FecdasPartesBundle_anularpeticio:
    pattern:  /anularpeticio
    defaults: { _controller: "FecdasPartesBundle:Admin:anularpeticio" }
    requirements:
        _method:  GET

FecdasPartesBundle_imprespeticio:
    pattern:  /imprespeticio
    defaults: { _controller: "FecdasPartesBundle:Admin:imprespeticio" }
    requirements:
        _method:  GET

FecdasPartesBundle_pagamentpeticioconfirm:
    pattern:  /pagamentpeticioconfirm
    defaults: { _controller: "FecdasPartesBundle:Admin:pagamentpeticioconfirm" }
    requirements:
        _method:  GET
        
        
FecdasPartesBundle_ajaxclubsnoms:
    pattern:  /ajaxclubsnoms
    defaults: { _controller: "FecdasPartesBundle:Admin:ajaxclubsnoms" }
    requirements:
        _method:  GET

FecdasPartesBundle_assegurats:
    pattern:  /assegurats
    defaults: { _controller: "FecdasPartesBundle:Page:assegurats" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_partes:
    pattern:  /partes
    defaults: { _controller: "FecdasPartesBundle:Page:partes" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_llicenciesParte: 
    pattern:  /llicenciesParte
    defaults: { _controller: "FecdasPartesBundle:Page:llicenciesParte" }
    requirements:
        _method:  GET

FecdasPartesBundle_historialLlicencies: 
    pattern:  /historialLlicencies
    defaults: { _controller: "FecdasPartesBundle:Page:historialLlicencies" }
    requirements:
        _method:  GET

FecdasPartesBundle_busseig:
    pattern:  /consultadni
    defaults: { _controller: "FecdasPartesBundle:Page:busseig" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_parte:
    pattern:  /parte
    defaults: { _controller: "FecdasPartesBundle:Page:parte" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_renovar:
    pattern:  /renovar
    defaults: { _controller: "FecdasPartesBundle:Page:renovar" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_pagament:
    pattern:  /pagament
    defaults: { _controller: "FecdasPartesBundle:Page:pagament" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_importcsv:
    pattern:  /importcsv
    defaults: { _controller: "FecdasPartesBundle:Page:importcsv" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_confirmcsv:
    pattern:  /confirmcsv
    defaults: { _controller: "FecdasPartesBundle:Page:confirmcsv" }
    requirements:
        _method:  GET

FecdasPartesBundle_notificaciotest:
    pattern:  /notificaciotest
    defaults: { _controller: "FecdasPartesBundle:Page:notificaciotest" }
    requirements:
        _method:  GET|POST


FecdasPartesBundle_notificacio:
    pattern:  /notificacio
    defaults: { _controller: "FecdasPartesBundle:Page:notificacio" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_notificacioOk:
    pattern:  /notificacioOk
    defaults: { _controller: "FecdasPartesBundle:Page:notificacioOk" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_notificacioKo:
    pattern:  /notificacioKo
    defaults: { _controller: "FecdasPartesBundle:Page:notificacioKo" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_llicencia:
    pattern:  /llicencia
    defaults: { _controller: "FecdasPartesBundle:Page:llicencia" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_persona:
    pattern:  /persona
    defaults: { _controller: "FecdasPartesBundle:Page:persona" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_ajaxpoblacions:
    pattern:  /ajaxpoblacions
    defaults: { _controller: "FecdasPartesBundle:Page:ajaxpoblacions" }
    requirements:
        _method:  GET

FecdasPartesBundle_gettipuspartes:
    pattern:  /gettipuspartes
    defaults: { _controller: "FecdasPartesBundle:Page:gettipuspartes" }
    requirements:
        _method:  GET

FecdasPartesBundle_duplicats:
    pattern:  /duplicats
    defaults: { _controller: "FecdasPartesBundle:Page:duplicats" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_duplicatsform:
    pattern:  /duplicatsform
    defaults: { _controller: "FecdasPartesBundle:Page:duplicatsform" }
    requirements:
        _method:  GET
        
FecdasPartesBundle_pagamentpeticio:
    pattern:  /pagamentpeticio
    defaults: { _controller: "FecdasPartesBundle:Page:pagamentpeticio" }
    requirements:
        _method:  GET

FecdasPartesBundle_licensetopdf:
    pattern:  /license
    defaults: { _controller: "FecdasPartesBundle:PDF:licensetopdf" }
    requirements:
        _method:  GET

FecdasPartesBundle_partetopdf:
    pattern:  /printparte
    defaults: { _controller: "FecdasPartesBundle:PDF:partetopdf" }
    requirements:
        _method:  GET

FecdasPartesBundle_asseguratstopdf:
    pattern:  /printllistes
    defaults: { _controller: "FecdasPartesBundle:PDF:asseguratstopdf" }
    requirements:
        _method:  GET

FecdasPartesBundle_facturatopdf:
    pattern:  /printfactura
    defaults: { _controller: "FecdasPartesBundle:PDF:facturatopdf" }
    requirements:
        _method:  GET

FecdasPartesBundle_albaratopdf:
    pattern:  /printalbara
    defaults: { _controller: "FecdasPartesBundle:PDF:albaratopdf" }
    requirements:
        _method:  GET

FecdasPartesBundle_albarapeticio:
    pattern:  /albarapeticio
    defaults: { _controller: "FecdasPartesBundle:PDF:albarapeticio" }
    requirements:
        _method:  GET

FecdasPartesBundle_facturapeticio:
    pattern:  /facturapeticio
    defaults: { _controller: "FecdasPartesBundle:PDF:facturapeticio" }
    requirements:
        _method:  GET

FecdasPartesBundle_checkrenovacio:
    pattern:  /checkrenovacio
    defaults: { _controller: "FecdasPartesBundle:Cron:checkrenovacio" }
    requirements:
        _method:  GET

FecdasPartesBundle_renovarllicencia:
    pattern:  /renovarllicencia
    defaults: { _controller: "FecdasPartesBundle:Cron:renovarllicencia" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_checkclubs:
    pattern:  /checkclubs
    defaults: { _controller: "FecdasPartesBundle:Cron:checkclubs" }
    requirements:
        _method:  GET

FecdasPartesBundle_checkupdatepreu:
    pattern:  /checkupdatepreu/{maxid}
    defaults: { _controller: "FecdasPartesBundle:Cron:checkupdatepreu" }
    requirements:
        _method:  GET

FecdasPartesBundle_checkpendents:
    pattern:  /checkpendents
    defaults: { _controller: "FecdasPartesBundle:Cron:checkpendents" }
    requirements:
        _method:  GET
        
FecdasPartesBundle_checkpartesdia:
    pattern:  /checkpartesdia
    defaults: { _controller: "FecdasPartesBundle:Cron:checkpartesdia" }
    requirements:
        _method:  GET

FecdasPartesBundle_informesaldos:
    pattern:  /informesaldos
    defaults: { _controller: "FecdasPartesBundle:Cron:informesaldos" }
    requirements:
        _method:  GET
        
FecdasPartesBundle_enquestes:
    pattern:  /enquestes
    defaults: { _controller: "FecdasPartesBundle:Enquestes:enquestes" }
    requirements:
        _method:  GET

FecdasPartesBundle_enquesta:
    pattern:  /enquesta
    defaults: { _controller: "FecdasPartesBundle:Enquestes:enquesta" }
    requirements:
        _method:  GET|POST


FecdasPartesBundle_tancarenquesta:
    pattern:  /tancarenquesta
    defaults: { _controller: "FecdasPartesBundle:Enquestes:tancarenquesta" }
    requirements:
        _method:  GET

FecdasPartesBundle_estadistiques:
    pattern:  /estadistiques
    defaults: { _controller: "FecdasPartesBundle:Enquestes:estadistiques" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_estadistiquestab1:
    pattern:  /estadistiquestab1
    defaults: { _controller: "FecdasPartesBundle:Enquestes:estadistiquestab1" }
    requirements:
        _method:  GET

FecdasPartesBundle_estadistiquestab2:
    pattern:  /estadistiquestab2
    defaults: { _controller: "FecdasPartesBundle:Enquestes:estadistiquestab2" }
    requirements:
        _method:  GET


FecdasPartesBundle_enquestausuari:
    pattern:  /enquestausuari
    defaults: { _controller: "FecdasPartesBundle:Enquestes:enquestausuari" }
    requirements:
        _method:  GET|POST

FecdasPartesBundle_enquestaresultats:
    pattern:  /enquestaresultats
    defaults: { _controller: "FecdasPartesBundle:Enquestes:enquestaresultats" }
    requirements:
        _method:  GET


        