parameters:
#    fecdas.example.class: FecdasBundle\Example

services:
#    fecdas.example:
#        class: %fecdas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    fecdas.twig.partes_extension:
        class: FecdasBundle\Twig\FecdasExtension
        tags:
            - { name: twig.extension }